### ISSUE TITLE
Audio Detune (now wide browser support)

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-feature-requests#135]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

Add the web audio API detune. This is useful to change pitch without changing length of the sound.

### Possible workarounds or alternatives

Import sound pitch shifted, download size and maintainability suboptimal.
Change playback rate, but that changes length of the sound.

### Proposed solution

Add the web audio API detune, as it now has wide browser support according to https://developer.mozilla.org/en-US/docs/Web/API/AudioBufferSourceNode/detune

### Why is this idea important?

Change pitch of a sound without changing its length, useful for adding variance to sound effects and games with music elements (i.e. you can play a piano in game)

**Comment by F3der1co** [comment]
edit: I am not sure if detune doesn't affect playback rate as well anymore

**Comment by Jase0000** [comment]
Deeply interested in this, I'm praying it's a trivial thing to add, but understood if not.

Iirc depending on if you have audio in Sounds or Music folder, it will do different effects when using the PlaybackRate, I believe it time-stretches with no pitch shift for Music, and pitches up/down for Sounds.

I believe this was the case, as I opted for putting my music in the Sounds folder for this very reason (wanted pitch shifting), which I do understand could be a very bad idea, especially if music is very long and gets loaded into memory.

**Comment by Wackytoaster** [comment]
Yes please :)

**Comment by AshleyScirra** [comment]
I prototyped this but quickly found out that the Web Audio API actually does not support pitch shifting at all at the moment. The `detune` parameter works the same as `playbackRate` - it just works in different units (cents instead of a ratio). So unfortunately the proposal is incorrect in stating that there is now a broadly supported API that can do pitch shifting. A further complication is that Construct plays music tracks with HTMLAudioElement instead of the Web Audio API, and that interface does not provide a detune parameter, so even if it did work as expected with the Web Audio API, it would only be supported for sounds and not for music - which I believe would be a new inconsistency, as IIRC all existing audio features work equally for sounds and music.

HTMLAudioElement does have a `preservesPitch` property which allows choosing whether altering the playback rate affects pitch or keeps the same pitch. However this does not allow an arbitrary pitch shift, and the Web Audio API does not appear to have any equivalent.

Pitch shifting audio appears to be a complex algorithm (granular synthesis came up in my research, and I think there are other approaches). It is probably possible to implement a custom pitch shifting algorithm with audio worklets, but I'd prefer not to build in such an approach, as it means integrating a complex library, and then has long-term compatibility implications if browsers do add the necessary feature but with a different approach. So I would prefer to only make this built-in if it's provided by a built-in browser API. Meanwhile it's possible to explore the custom audio processing approach with Construct's JavaScript coding feature, as you can access all the same browser APIs with that.

For this to be implementable I think there are two approaches that could do it:
- both HTMLAudioElement and Web Audio API add support for a parameter that does actually do pitch shifting (which `detune` currently does not), perhaps both including a `preservesPitch` setting
- the Web Audio API adds support for a pitch-shifting node (which can cover HTMLAudioElement as its audio output can be piped in to the Web Audio API)

Either way this will need a change to the specification and support added by browsers. The relevant spec issues appear to be:
https://github.com/WebAudio/web-audio-api/issues/2443
https://github.com/WebAudio/web-audio-api/issues/2487

Therefore I'm afraid this is not something we will consider implementing until the necessary web APIs are in place, so closing this request as declined. If the necessary web APIs are added, you can re-post this and we will reconsider.

(On a side note: this is a classic example of how [a simple-looking feature ends up being complicated](https://www.construct.net/en/blogs/ashleys-blog-2/unexpected-complications-1535), and it also illustrates how much prototyping and research work an apparently simple-looking feature request can end up taking, which is why it is difficult for us to respond to feature requests given we receive hundreds of them.)

**Comment by F3der1co** [comment]
The description on the MDN web docs made it sound like it does just do pitch shifting, but apparently that's not the case.
Thanks for the update and prototyping it. I hope this comes one day.
