### ISSUE TITLE
Sprite editor color palette save/load

### ISSUE THREAD

**Issue by TackerTacker** [Scirra/Construct-feature-requests#178]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

The ability to save and load different color palettes in the sprite editor.
Currently the color palette is global and I can only make a single color palette, if I change anything it affects all projects.

### Possible workarounds or alternatives

There is no workaround as far as I know.

### Proposed solution

A way for me to save a color palette I've created in C3 and load it back up later.
Additionally it would be nice to load some known color palette formats like .GPL (Gimp), .ASE (Adobe), .hex, basically some of the formats available for download [here](https://lospec.com/palette-list). 
But that's just a nice to have, not a must have, the saving and loading of palettes made in C3 is the most important part.

### Why is this idea important?

Making color palettes in C3 is really tedious, which isn't great but if you only have to do it once it's not the end of the world, 
but since it is global you need to either stick with one palette forever or have to redo a palette over and over again. 
I also had it happen that my color palette was just gone, idk how it happened but it was just gone and I didn't make a screenshot of it so it was gone gone. 
It would also be great for the C3 community to be able to share their color palettes.

**Comment by Pigpud** [comment]
Definitely would be useful.

**Comment by CtrlAnt** [comment]
It will be very useful. But they also need to increase the maximum of color we can add.

**Comment by Pigpud** [comment]
Agreed!

**Comment by DiegoScirra** [comment]
This will be added on the first beta release after the upcoming stable release.

When it comes to importing palettes from a file, we decided to not support any specific format because properly supporting those files is potentially very difficult to get right in all cases. Instead C3 will be able to load a very simple JSON file with an array of colors that can be defined in most formats supported by CSS.

This is an example of the file that C3 will support, in the following case the colors are hexadecimal RGB.

```
{
	"palette": ["ff0000", "00ff00", "0000ff", "00ffff", "ff00ff"]
}
```

Other formats could be used too, for example:

```
{
	"palette": ["rgba(100%, 0%, 0%, 1)", "rgba(0%, 100%, 0%, 1)", "rgba(0%, 0%, 100%, 1)"]
}
```

The format is extremely simple so it shouldn't be too much of a problem to generate the file.

**Comment by AshleyScirra** [comment]
Support for saving/loading color palettes is now supported in [r417](https://www.construct.net/en/make-games/releases/beta/r417).
