### ISSUE TITLE
Add support for access to glMatrix library already included in C3 runtime (scripting, addon)

### ISSUE THREAD

**Issue by MikalDev** [Scirra/Construct-feature-requests#194]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

Similar, but not the same to #192 . Add official support for dev use of the the glMatrix library (globalThis.glMatrix in the runtime.)

This will allow for nice vec and mat math usage by addons and scripting (very handy for 2d and 3d math.)

### Possible workarounds or alternatives

Include _another_ version of glMatrix for each addon and another for scripting (e.g. 3+ versions.)

### Proposed solution

Sanction usage / access of glMatrix included in runtime by whatever method makes sense for C3.

### Why is this idea important?

This will allow for nice vec and mat math usage by addons and scripting (very handy for 2d and 3d math.) Important for more complex C3 games for object movement, rotation, etc.

**Comment by AshleyScirra** [comment]
A benefit of bundling your own glMatrix library is it will not break if we upgrade the internal glMatrix library (which could include a major version update which is not backwards compatible). In that sense, it is better for long-term maintenance and avoiding the risk of breaking projects due to upgrading internal code if you do bundle your own glMatrix library. We don't want to end up in a situation where we're stuck on an old version of glMatrix with the engine and cannot upgrade it due to breaking too many things.

**Comment by MikalDev** [comment]
thanks for the response, closing
