### ISSUE TITLE
[SDK 2.0] Add-on version constraints

### ISSUE THREAD

**Issue by LuanHimmlisch** [Scirra/Construct-feature-requests#256]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

Being able to configure versions constraints to Addons, to prevent Addons being used in a specific Construct version.

### Possible workarounds or alternatives

There's no current alternative.

### Proposed solution

Add a key `requires` or similar to the `addon.json` where you can set a version constraint, maybe similar to the constraints' convention from [Composer](https://getcomposer.org/doc/articles/versions.md#version-range) or NPM or similar packaging tools:

![image](https://github.com/Scirra/Construct-feature-requests/assets/46875694/c5988e31-bbfd-4542-b0a9-b774ec5a2221)

By default, if the key is not added, it would mean any version, similar to:

![image](https://github.com/Scirra/Construct-feature-requests/assets/46875694/2310d2ac-50fd-4187-b669-6f5968a51e8e)

If an installed plugin doesn't meet the constraints of the current version, it would be hidden/unloaded to prevent the usage of said plugin.

---

If the Composer convention is too hard to do, both `minVersion` and `maxVersion` keys could be added instead as a simpler way:
![image](https://github.com/Scirra/Construct-feature-requests/assets/46875694/1831fae5-2988-45c9-90a8-3cd7b7d6131b)

### Why is this idea important?

This allows add-on developers to have control over their plugins and how they are used, by enforcing strict rules. 

This should prevent users from having errors because of breaking changes and should prevent a major part of the support emails that are sent to Scirra.

**Comment by skymen** [comment]
I want to add that this is also very important because one big historical limitation of addons in C3 is that it's very common for new versions of the old SDK to add a new feature (say z elevation, 3d, scene graph) and if a new addon tells C3 where it stands in regards to that new feature, then that addon crashes any previous C3 version, even by virtue of being installed.

For example, I sometimes help with big projects that have been version locked for a long time, and just opening that version of C3 on my main browser crashes it.

It is also important to provide addons with the context of what version of the engine they are running on so they can do these adjustments when code is ran, which would make it a lot easier to maintain one code base that keeps working in the long run, while staying backwards compatible with previous versions of the engine.

**Comment by AshleyScirra** [comment]
The goal of the addon SDK v2 is to be forwards-compatible forever. So there should not be any breakage with addons in future versions, and if there was, it would be our responsibility to fix it. Given that, it only makes sense to specify a minimum Construct version requirement. I suppose we could do that - but given most users are on the latest stable release, is that really a significant problem?

**Comment by NickR-Git** [comment]
> The goal of the addon SDK v2 is to be forwards-compatible forever. So there should not be any breakage with addons in future versions, and if there was, it would be our responsibility to fix it. Given that, it only makes sense to specify a minimum Construct version requirement. I suppose we could do that - but given most users are on the latest stable release, is that really a significant problem?

It's a significant problem for, as was stated, projects that may be version locked - not uncommon in game development even at large studios, and not due to addons - but some older versions of/older addons cause C3 to completely crash on opening the project, preventing the project from being opened at all in a newer version - that sounds significant.

**Comment by skymen** [comment]
> Given that, it only makes sense to specify a minimum Construct version requirement.

I don't agree, what happens if you do break things? What happens if some feature changes in the future which creates a side effect that needs to be addressed? What happens if you decide to add a new engine feature that now needs to be accounted for? What if my addon keeps working but past a given version there is a new way to achieve the same thing that is done by a future version of the addon and I want users to move to that new version?

Would it really be so hard to provide a GetProjectRuntimeVersion method that returns a string or a number? Even if it's not ever needed, I can't see any good reason not to do it regardless. It's a simple, industry standard feature that is specifically there to help deal with issues you cannot see coming (and, had SDK v1 had this feature implemented, this whole situation would probably not have happened in the first place)

**Comment by skymen** [comment]
Unity provides multiple ways for package developers to adapt their code to the context in which it's ran.

Unity version at runtime: https://docs.unity3d.com/ScriptReference/Application-unityVersion.html
Unity version at compile time: https://docs.unity3d.com/Manual/PlatformDependentCompilation.html

These would be used to gate the maximum version if needed, or to address issues only present in specific versions of the engines, or to provide a compatibility mode for an older version you might still want to support.

The manifest does only provide a minimum version requirement (for the same reason you outlined i.e. in theory given the addon respects the API it should keep working forever) but this only prevents addons from appearing in the list, not from being installed:
https://docs.unity3d.com/Manual/upm-manifestPkg.html

In fact this is the way Unity's team develops their own core packages:
https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@14.0/manual/requirements.html

**Comment by AshleyScirra** [comment]
Isn't it better though if things are forwards compatible? Surely normal users don't want to have to be forced to upgrade addons, and version match different components (and things don't work if you make a mistake), just to update to the latest version of Construct? If it were me, I'd much prefer it if everything just kept working in the long run. (I know we're making a switch, but the Addon SDK v1 does not guarantee long-term compatibility; the Addon SDK v2 does.)

In my view Unity seem to have made a big mess if their component management is that complicated. Isn't it better if we avoid replicating that?

**Comment by AshleyScirra** [comment]
As of [r394](https://www.construct.net/en/make-games/releases/beta/r394) addons using the SDK v2 can now specify a `"min-construct-version"` field in addon.json, e.g. `"min-construct-version": "r395"`. Construct will prevent installation of addons (or loading them if installed with a different version) if the minimum required version is higher than the version of Construct used.

We will not implement a maximum version. If you really want to replace an addon with another one, deprecate the addon (which removes it from listings) and publish a new addon with a different ID to replace it. The deprecation system is intended to avoid the backwards compatibility problems that would occur if addons could not be used in newer versions of Construct, as that would block people opening projects using the addon, which only makes it harder for people to remove the addon from their project.
