### ISSUE TITLE
[SDK 2.0] Efficient way to draw vertices mesh

### ISSUE THREAD

**Issue by MikalDev** [Scirra/Construct-feature-requests#262]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

This is from the Esoteric Software Spine Team to do an official port of Spine runtime to C3 SDK w/o the using the current Spine webgl renderer in the C3 webgl renderer context.

If this is supported Spine will work with webGPU and webGL and use only the official C3 SDK V2

"What we need is a method/function that looks like this:

drawVertices(positions, uvs, colors, indices, blendMode)
Where:

positions is an array of numbers (x, y coordinates)
uvs is an array of numbers (u, v coordinates, same length as positions)
colors is an array of numbers (ideally 32-bit rgba "ints", otherwise 4 floats r, g, b, a)
indices is an array of numbers, 3 consecutive numbers represent indices into the other arrays forming a triangle
texture depends on what type C3 uses to represent textures used on the GPU. Would basically map to an image in the atlas used by the skeleton
blendMode depends on what's available in C3
That'd be the most minimal thing we'd need which wouldn't support two-color tinting. We could also conform to whatever internal vertex/indices format is used in C3's batcher of course, as long as we can specify vertex positions, uvs, and colors.

QUAD3D and consorts would be way to inefficient, batching not withstanding. E.g. Spineboy is a few hundred triangles. That'd mean we'd have to create a few hundred instances of QUAD3D, which would have to be batched, etc. pp. That's a lot of work that's not necessary, as we already have all the data in a form that is mostly simple to submit in one go to the GPU."

They are open to different specific methods, but the crux is to make it efficient to draw a larger mesh.

### Possible workarounds or alternatives

Current workaround is to use webGL renderer in same context as C3 renderer and render to C3 texture directly (need to use internal access to texture)

Other possible workaround is use Quad3D, which is slower.

### Proposed solution

drawVertices(positions, uvs, colors, indices, blendMode)
Where:

positions is an array of numbers (x, y coordinates)
uvs is an array of numbers (u, v coordinates, same length as positions)
colors is an array of numbers (ideally 32-bit rgba "ints", otherwise 4 floats r, g, b, a)
indices is an array of numbers, 3 consecutive numbers represent indices into the other arrays forming a triangle
texture depends on what type C3 uses to represent textures used on the GPU. Would basically map to an image in the atlas used by the skeleton
blendMode depends on what's available in C3
That'd be the most minimal thing we'd need which wouldn't support two-color tinting. We could also conform to whatever internal vertex/indices format is used in C3's batcher of course, as long as we can specify vertex positions, uvs, and colors.

This would also be very useful for the 3DObject addon and other addon which use mesh.

### Why is this idea important?

Spine 3D is a very useful tool for 2D animation for C3. Many users use the C3 webgl renderer version today and want to continue to use it as SDK V2 becomes the only SDK option.

**Comment by WilsonPercival** [comment]
Similar proposal https://github.com/Scirra/Construct-feature-requests/issues/170

**Comment by MikalDev** [comment]
The proposals are not that similar. The previous proposal requested that C3 implement the entirety of the C3 spine runtime in C3.

This request is to add one SDK V2 draw feature and the C3 Spine Addon and Runtime will be created by a 3rd party, not the C3 team. Very different scope of work.

**Comment by MikalDev** [comment]
In terms of implementation, perhaps the drawVertices could generate it's own batch, so it will not need to create complications with mixing in with the current draw commands submitted to a  batch.

**Comment by AshleyScirra** [comment]
Construct's renderer currently doesn't support per-vertex colors - the WebGPU renderer does support per-quad colors though. It also uses a static index buffer to optimize rendering quads specifically. So at the moment we can't easily just add an API on top of the existing renderer - we would probably have to rearchitect the renderer to some extent to fully support the proposed method. As Construct's renderer is currently geared towards maximizing quad rendering performance, rearchitecting it to have things like per-vertex colors and dynamic indices would probably actually make rendering less efficient for existing projects that do mainly just render quads, so I think there is a non-trivial performance trade-off with that.

For Construct's own mesh distortion feature we just render by issuing a bunch of quads and it works with pretty good performance - to be clear, each call is not a separate batch, you can issue 100 calls to Quad() or variants and the renderer internally batches it all up in an efficient way, and both Construct and modern JavaScript are so fast you can easily get tens of thousands of quads per frame even on older devices - and bear in mind a quad is a pair of triangles, so a few hundred triangles should not be a problem. So on the basis some support is better than none, I would suggest developing a Spine addon anyway, but emulating the proposed `drawVertices` method as best as possible with individual Quad() calls; if that isn't fast enough and/or we do add this in future, then it should be easy to switch the emulated method over to a new built-in method.

**Comment by MikalDev** [comment]
I understand, I will work with the devs and see if something is possible and I will also benchmark performance for them using 3DObject, which does implement a similar drawVertices wrapper (but without the vertex color, instead it uses the C3 setcolor per mesh). We'll see if it runs well enough to warrant further work on an official addon for C3.

I will close this request. I do plan on opening another request about using vertex for color, so it does not break the batch in webgl (I thought in the past we had this for one brief point in time in webgl also, I remember looking at the stock fragment shader and seeing color was coming in through a vertex, right?). If the performance data I show with 3DObject does not work well enough for Spine rendering, I will open a new request with a discussion of the results.

**Comment by MikalDev** [comment]
Request not planned by Scirra.

**Comment by MikalDev** [comment]
@AshleyScirra I know this is closed, but can you please take a look at my benchmarking on the esoteric forum and do a sanity check:

https://esotericsoftware.com/forum/d/26169-official-c3-addon--runtime/10

I am trying to convince ourselves that we may still get something usable with using Quad* interface for now (ignoring color).

**Comment by AshleyScirra** [comment]
> I do plan on opening another request about using vertex for color, so it does not break the batch in webgl (I thought in the past we had this for one brief point in time in webgl also, I remember looking at the stock fragment shader and seeing color was coming in through a vertex, right?). Is there a reason this was reverted or not considered for webgl?

I don't recall C2 or C3 ever having per-vertex or per-quad colors in their WebGL renderers. Perhaps things were different years ago, but if they were, I don't remember. WebGPU however does have per-*quad* colors.

The reason for this is to optimize the way most Construct projects work: you can send a per-vertex color, but now rendering every single sprite is slightly slower. That work is wasted if everything (or even just most things) has the default color, which is the case in a lot of projects. In WebGL we made a trade-off where the color can be changed, but it breaks the batch; this means rendering default-color content is faster, but rendering different-color content is slower - a suitable tradeoff for most Construct projects. In WebGPU, the more advanced capabilities allow for a vertex pulling technique where we can submit just a single color per quad, so we can hit a sweet spot where only one color needs to be submitted per quad (a quarter of the extra work of per-vertex colors) and it stays batched, so color-varying benchmarks are way better. In terms of Construct's built-in features, that's a nice design, as you can only set the color for entire sprites, so there is no need to submit a color for every vertex. However it does corner us a bit with extensibility and trying to do things like submit meshes with per-vertex colors.

We could add a different rendering mode specifically for meshes, but then switching render mode breaks the batch, which has its own performance pitfalls.

> I know this is closed, but can you please take a look at my benchmarking on the esoteric forum and do a quick sanity check:

The numbers there seem reasonable. I think you could have budget a few thousand triangles even on low-end mobile devices. It's 2024, not 2014 - a few hundred triangles in a mesh is not that heavy a performance overhead these days. I was going to point out the 3D model rendering as a good example - just issuing one triangle at a time with degenerate quads appears to run surprisingly well, even without any built-in support for meshes!

There's lots of tricky trade-offs with performance. Perhaps we should change our trade-offs, but that means some fairly tricky work refactoring two renderers. If I could click my fingers and have this done, I'd do it - it's just we have had about 4 year's work submitted here in about 4 months, and we've just kicked off a long and complex project to move to a new addon SDK, etc. I know the Esoteric devs might be puzzled as to why our renderer doesn't already have this - the reason is mainly, as ever, having far, far more work proposed than we could possibly do, even if we'd love to do it all. Degenerate quads may be imperfect, but it's a pragmatic way forward, it may well work out surprisingly effective in 2024, and it can always be improved later.

**Comment by AshleyScirra** [comment]
Tell you what - it makes sense to do the emulation inside Construct's own renderer where it's probably a bit faster, and it's fairly easy to write. So the next beta has a `drawMesh(posArr, uvArr, indexArr)` method, where:

posArr is array of [x, y, z]
uvArr is array of [u, v]
indexArr is array of [i, j, k]

For example in the drawingPlugin sample you can replace the call to `renderer.quad3(quad, rcTex)` with this and it renders the texture twice with a skew:

```js
const posArr = [
	[quad.p1.x + 50, quad.p1.y, 0],
	[quad.p2.x + 50, quad.p2.y, 0],
	[quad.p3.x, quad.p3.y, 0],
	[quad.p4.x, quad.p4.y, 0],
	
	[quad.p1.x + 250, quad.p1.y, 0],
	[quad.p2.x + 250, quad.p2.y, 0],
	[quad.p3.x + 200, quad.p3.y, 0],
	[quad.p4.x + 200, quad.p4.y, 0]
];

const uvArr = [
	[rcTex.left, rcTex.top],
	[rcTex.right, rcTex.top],
	[rcTex.right, rcTex.bottom],
	[rcTex.left, rcTex.bottom],
	[rcTex.left, rcTex.top],
	[rcTex.right, rcTex.top],
	[rcTex.right, rcTex.bottom],
	[rcTex.left, rcTex.bottom]
];;

const indexArr = [
	[0, 1, 2],
	[0, 2, 3],
	
	[4, 5, 6],
	[4, 6, 7],
];

renderer.drawMesh(posArr, uvArr, indexArr);
```

It doesn't do per-vertex colors, since as discussed it would take more work to do that, but it can do the textured mesh drawing, including in 3D. As it moves the implementation to Construct's own renderer, any future optimizations can be done as an internal change and addons won't need changing. It also gives us scope to do something like proper mesh submission in the WebGPU renderer only while leaving WebGL with an emulated implementation, to be ultimately phased out. So hopefully that's at least a bit of an improvement on the current situation.

**Comment by MikalDev** [comment]
We'll take it! I think it's a great start and keeps the opportunity open in the future, as you say, for C3 internal improvements vis-a-via webGpu renderer. Thanks! I appreciate the discussion and the work. I am also looking forward to an official C3 Spine addon from Esoteric SW. I think the general C3 game dev community (and perhaps C3 Animate community) will appreciate having a full featured, well supported, advanced 2D animation tool.

**Comment by AshleyScirra** [comment]
Yeah, I realized afterwards typed arrays are probably faster and also would be faster with built-in mesh rendering in future, as it could potentially just copy them directly to the GPU. So I've changed it to work with typed arrays like this:

```js
const posArr = new Float32Array([
	quad.p1.x + 50, quad.p1.y, 0,
	quad.p2.x + 50, quad.p2.y, 0,
	quad.p3.x, quad.p3.y, 0,
	quad.p4.x, quad.p4.y, 0,
	
	quad.p1.x + 250, quad.p1.y, 0,
	quad.p2.x + 250, quad.p2.y, 0,
	quad.p3.x + 200, quad.p3.y, 0,
	quad.p4.x + 200, quad.p4.y, 0
]);

const uvArr = new Float32Array([
	rcTex.left, rcTex.top,
	rcTex.right, rcTex.top,
	rcTex.right, rcTex.bottom,
	rcTex.left, rcTex.bottom,
	
	rcTex.left, rcTex.top,
	rcTex.right, rcTex.top,
	rcTex.right, rcTex.bottom,
	rcTex.left, rcTex.bottom
]);

const indexArr = new Uint16Array([
	0, 1, 2,
	0, 2, 3,
	
	4, 5, 6,
	4, 6, 7,
]);

renderer.drawMesh(posArr, uvArr, indexArr);
```

**Comment by AshleyScirra** [comment]
The [r393](https://www.construct.net/en/make-games/releases/beta/r393) release now has a `drawMesh()` method which works as described in my previous comment. I think that covers the basic API for now, albeit without per-vertex colors as that is a more complicated addition (which could be filed as a follow-up request), and without direct submission to the GPU, but performance is probably good enough. In future if it needs to be made even faster, it can be done as an internal renderer optimization and so addons using it should not need changing.

**Comment by MikalDev** [comment]
Thank you! This is appreciated and we'll measure perf through development and give feedback. I will 'stage' the vertex color request. Most important is per tri/quad, which I think will be more straightforward for C3.
