### ISSUE TITLE
[SDK 2.0] add access to mesh point data

### ISSUE THREAD

**Issue by MikalDev** [Scirra/Construct-feature-requests#283]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

Similar to the ACE request #97 , add SDK access to the IWorldInstance mesh data (x,y,zElevation per point). Would be nice to get an array or array of arrays for faster processing, but even a getter with row,col parameters would work.

### Possible workarounds or alternatives

None, for example if the points are set in the layout, events would not know the current values.

### Proposed solution

Add SDK API to access the mesh points via an array of arrays or each element using row, col parameters.

### Why is this idea important?

Allows addons to change behavior based on the mesh values (e.g. collision, ground hugging, etc.)

### Additional remarks

There are already some mesh distortion SDK APIs, but this one is not yet available. It is also ok if this is read only. Since we already have the set API.

**Comment by MikalDev** [comment]
```
        _getMeshPoints(worldInfo) {
            const cannon = globalThis.Mikal_Cannon;
            const wi = worldInfo;
            const points = wi?._meshInfo?.sourceMesh?._pts;
            const width = wi.GetWidth();
            const height = wi.GetHeight();
            const meshPoints = [];
            for (const rows of points) {
                const meshRow = [];
                for (const point of rows) {
                    const x = point._x * width;
                    const y = point._y * height;
                    const z = point._zElevation;
                    meshRow.push({ x, y, z });
                }
                meshPoints.push(meshRow);
            }
            return meshPoints;
        }```

This is how I currently use them and would like an official SDK V2 method to access them instead.

**Comment by skymen** [comment]
I also agree this would help quite a lot. I have been messing a lot with Sprite mesh data for 3D applications, and over and over again, not being able to read back that data has been an issue. So much so that I would prefer if this was a feature in Construct in general for events, scripting AND the sdk.

Here are a list of things I have worked on in the past that would benefit from getting this feature.

Trail Renderer:
My trail addon has been used in many projects, and currently has its own system to keep in memory the points. It would make the code far cleaner if I could remove most of that point memory handling. It would also make the addon work better when integrated with events that could decide to change the mesh data.
https://www.construct.net/en/make-games/addons/531/trail-renderer

Text Mesh:
The mesh feature when used with text brings a very useful feature: decoupling the text's canvas size from its real size in the game. This allows for stretch, skew and even 3D rotations of the text.
I've used this a lot in games for diegetic UI. Here are two examples. One from Idle Ants, a game I made for Madbox in 2021
![image](https://github.com/Scirra/Construct-feature-requests/assets/11213825/894cb621-7cc0-4132-8889-5ca794562c61)

And here is another example from a game I'm currently working on:
![image](https://github.com/Scirra/Construct-feature-requests/assets/11213825/30fd76d5-a482-4e8e-b07b-4a4df52f0144)

Mesh for slopes and physics:
In the past I've used meshes to import data from crocotile. This is pretty impressive and the proof of concept shows C3 can probably run a full game based on this workflow, however currently since there is no way to get back mesh data, it's very hard to integrate with physics engine, or even a custom physics system.
https://x.com/skymen75/status/1724268059962335369

I'm facing the same issue right now where Federico implemented a system to handle slope physics in 3D
https://github.com/Scirra/Construct-feature-requests/assets/11213825/5be69d7c-c1f1-4282-8093-e4deb8498842
And we'd really like to be able to use 3D mesh to create slopes, but we can't because the information is not accessible.

In the same vein, this would be very very helpful for a custom physics system I wanted to work on for a motorbike game I had in mind:
![image](https://github.com/Scirra/Construct-feature-requests/assets/11213825/c515c577-3dbd-470e-be51-7eae766fd277)

C3's current physics engine is not good enough to handle the collision for me, and if I have to implement a new one, i'd rather create my own physics system rather than implement a 3rd party one. But for that I need to have access to mesh (and also collision point) data so I can do the collision math. Otherwise, I'll have to rely on the "is overlapping" and raycasting features provided by C3 and it wouldn't really allow me to have as much control as I'd want to have on this.

Mesh for Character animations:
I worked a while ago on a bone system for a character animation system for a game I wanted to prototype:
https://github.com/Scirra/Construct-feature-requests/assets/11213825/e20eb88f-40d1-4c5f-91b4-03092972bd4f

Most of the things I showed are possible now, but they rely on the fact that I'd be able to make a copy of the points information (or use an alternate system instead), but if I need to write a system or an addon that works with meshes outside of my control, or meshes created within the editor, I cannot do that, and I think that severely limits what can be achieved using meshes.

**Comment by AshleyScirra** [comment]
A new `getMeshPoint()` method is now available in [r401](https://www.construct.net/en/make-games/releases/beta/r401).
