### ISSUE TITLE
Flowcharts: Node "templates"

### ISSUE THREAD

**Issue by LuanHimmlisch** [Scirra/Construct-feature-requests#285]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

Being able to set nodes as "templates" to reuse their structure by creating clones through the context menu.

### Possible workarounds or alternatives

Create the nodes you will use as templates and having them unconnected, and just copy and paste them

### Proposed solution

When right-clicking a node, a new option would appear called "Convert to template", this would set the node as a template and any in and out links and tag would be removed.

The templates appear in the Flowchart options in a list, as shown in the following mockup:
![image](https://github.com/Scirra/Construct-feature-requests/assets/46875694/91bce4d8-cae7-4273-9753-04ae60e6e4bc)

Then, the template nodes would appear in the "add node" context menu as part of the options:

- Add node
- Add reference node
- Add "Comparison Node" node
- Add "Animation Node" node

When added, it would clone the template's properties. 

**The scope of this suggestion doesn't cover maintaining the reference of the replicas and their templates, so if a template is updated, the "replicas" wouldn't. As the templates only serve in the creation process, and after that, the "replicas" are just normal nodes.**

### Why is this idea important?

Similar to other ideas about giving Construct structs, the proposed solution makes the reutilization of flowchart-based system between the same and other projects and the maintainability of the same a lot better.

### Additional remarks

A would-be-nice, could be adding the replicas saving their original template reference, however, as this would be more difficult, I don't necessarily think is part of the scope of the suggestion as mentioned previously.

**Comment by DiegoScirra** [comment]
I am looking at possibly implementing this but as I think about it, it seems like it is largely already possible to do.

Here are a few things that don't quite add up for me:

1. Having template nodes as part of the flowchart they were created in seems limiting. I am imagining that the first thing people would want is for node templates to be part of the whole project rather than a flowchart.

2. If the template nodes where part of the whole project, I was thinking that they could be added to a new special sub folder of the main **Flowcharts** folder, a bit like how the main **Timelines** have the special **Eases** sub folder. Following that path I thought that creating a node template would basically create a special kind of flowchart which would be placed in this new sub folder, you would then be able to edit the templates like any other flowchart.

It's at this point were I think it's already possible to do the whole workflow, it's just not explicit. In a very similar way to Object bank Layouts, you can have a Flowchart which is only created to hold template nodes. When you need one you can open the bank and just copy and paste it where you need it.

**Comment by DiegoScirra** [comment]
I thought a little bit more about this and added some new functionality to be able to set any node in any flowchart as a "Preset". Went with that term instead of "Template" because we already use that for a different feature.

Starting in the next beta, **r413**, you will be able to set a node as a preset from the Properties bar or from a node's context menu. Once a node is a preset a new option will appear in the main context menu to add nodes, which will open a dialog with all the preset nodes.

The dialog shows all the presets in all the flowcharts in the project, as a tree. The tree behaves as any other tree in C3, allowing you to create folders and sort the items as needed. The tree items are named using the corresponding node's caption.

After a preset is chosen, the newly created node is just like the original. At this point, the new node is completely independent from the preset, so changing the preset does not affect the new node.
