### ISSUE TITLE
Text:  Support CSS

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-feature-requests#294]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

Support custom CSS styles for text object so that we can make the text more customized.

For example: shadow, letter spacing.... and more!

### Possible workarounds or alternatives

Currently, although this can be done by **Update to HTML**, because HTML elements and Text are different objects, we will lose all the property in the Text object, such as position, font size, alignment, warp, etc. we need to re-design the CSS styles of all elements starting from zero.

This is frustrating and annoying for many people. It’s annoying.

I think this feature should reduce my work, not bring me extra workload.

### Proposed solution

Therefore, it would be very convenient if we can set CSS styles directly on Text object.

### Why is this idea important?

I think this feature will greatly improve the way UI works

### Additional remarks

https://github.com/Scirra/Construct-feature-requests/issues/242

**Comment by AshleyScirra** [comment]
Construct's text objects render directly to a canvas using JavaScript. It does not involve any HTML or CSS. This makes it infeasible to use CSS to style text, because the technology is simply not applicable in this case.

If you want to use the full capabilities of CSS with text, you can do that with the HTML Element object in Construct. However as noted you will need to use CSS for all properties of the text, including alignment etc.
