### ISSUE TITLE
Animation Editor: Load as Animation

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-feature-requests#42]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

Currently, images imported into the animation editor can only be used as frames. Wish there was an option to add each file as an animation. and use the file name as the animation name.

### Possible workarounds or alternatives

Pass

### Proposed solution

Pass

### Why is this idea important?

![Snipaste_2024-01-09_04-51-19](https://github.com/Scirra/Construct-feature-requests/assets/45864744/ae69f804-18d8-492b-ad8b-7e0264ca4550)

![Snipaste_2024-01-09_04-43-46](https://github.com/Scirra/Construct-feature-requests/assets/45864744/f5b3dfd5-f57f-47dd-a97f-1959a2746df9)

### Additional remarks

[RELATED IDEAS] use Files name as Animation Name https://github.com/Scirra/Construct-feature-requests/issues/41

**Comment by brushfe** [comment]
@AshleyScirra I've run into this situation many times, and would definitely vote for the ability to import as separate animations. 

I work a lot in the 8-bit style, where many sprite objects have unique artwork, but don't have animations. This would also help a ton in the prep work, since my art is thus organized by object, not in spritesheets.

It's important to think of this as a _sprite_ editor, not just an _animation_ editor, and there are many instances where animations aren't needed but unique sprites are.

**Comment by XHXIAIEIN** [comment]
> When would you need to import lots of single-frame animations?

For example
https://editor.construct.net/#open=farming-lines
![Snipaste_2024-01-18_00-57-33](https://github.com/Scirra/Construct-feature-requests/assets/45864744/2110a9b2-cc7d-4f89-95bc-8e1038539403)

https://editor.construct.net/#open=gift-guesser
![Snipaste_2024-01-18_00-51-21](https://github.com/Scirra/Construct-feature-requests/assets/45864744/fbff75ca-2dc1-4c09-9fa3-501b71c96f50)

https://editor.construct.net/#open=persistent-inventory
![Snipaste_2024-01-18_00-55-21](https://github.com/Scirra/Construct-feature-requests/assets/45864744/0bda6194-a215-4c22-b580-052cc3448a71)

**Comment by alastajj** [comment]
This could be achieved with the feature request that allows setting frame based on "tag"?

https://github.com/Scirra/Construct-feature-requests/issues/44

**Comment by LuanHimmlisch** [comment]
@AshleyScirra I've been myself in the same situation of wanting to import many graphics as different animations many times. Either because I wanted to be able to call them on code by name or because I'm using the object for any misc "static" graphic, like logos and any other thing that doesn't interact with the events, and wanted to have the dropdown with names. 

Basically, animations are not only animations; they're useful to organize and name graphics. And so, having the option to create them at once, would be a small addition but very useful.

**Comment by brushfe** [comment]
> This is already supported.
> 
> If you place all the images you want to be in the same animation into a zip file and then drop the zip file into the animations pane, an animation with the name of the zip file will be created. You can even drop multiple zip files at the same time. You can even pack each zip file with an optional configuration file with further details on how to import the images.
> 
> https://www.construct.net/en/make-games/manuals/construct-3/interface/animations-editor#internalH1Link7

@DiegoScirra I don't think this is the what's being requested. The images are meant to be imported as separate animations, not frames in a single animation. If that's not possible yet, could you re-open this feature request?

**Comment by XHXIAIEIN** [comment]
@DiegoScirra Place all the images into a zip and then drag the zip into the animation pane. You will only get 1 animation containing multiple frames, rather than creating separate animations for each file.

**Comment by DiegoScirra** [comment]
What I meant is you could rather quickly place each image in an individual zip file, then drop all those zip files in the animations panel and the importer would create a new animation with one frame for each zip file dropped.

If you have a lot of files you can use a tool like WinRAR to create an unique zip file for each file.

https://stackoverflow.com/questions/24932604/how-to-compress-each-subfolder-in-a-folder-into-a-separate-rar-archive-using-win

**Comment by XHXIAIEIN** [comment]
@DiegoScirra I think it would be more convenient if it could be supported in the editor, for example by Add an option in the 'Load Images from files' icon. That would greatly improve the work experience. Because this is a very common usage.

one more idea
![Snipaste_2024-02-27_23-28-45](https://github.com/Scirra/Construct-feature-requests/assets/45864744/125fe438-008b-488b-aaf0-ab384e7ef8f6)

**Comment by brushfe** [comment]
> What I meant is you could rather quickly place each image in an individual zip file, then drop all those zip files in the animations pane and the importer would create a new animation with one frame for each zip file dropped.
> 
> If you have a lot of files you can use a tool like WinRAR to create a unique zip file for each file.
> 
> https://stackoverflow.com/questions/24932604/how-to-compress-each-subfolder-in-a-folder-into-a-separate-rar-archive-using-win

I very much vote for @XHXIAIEIN's suggestion of having this supported in-editor. This is a common import need for many 2D game styles. 

Offloading the import to WinRAR (and directing basic users like myself to something as complex as StackOverflow) feels very out of touch with the typical ease & low skill requirements that Construct otherwise delivers.

Since this feature doesn't exist yet, @DiegoScirra could this request be re-opened? I'd hate to have it lost in the closed section (unless this is a hard no?)
