### ISSUE TITLE
Hierarchy View

### ISSUE THREAD

**Issue by OverboyDev** [Scirra/Construct-feature-requests#9]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

![HierarchyView_Mockup (1) (1)](https://github.com/Scirra/Construct-feature-requests/assets/99751718/0d57d8d2-c686-4a9f-84e2-a1b156ca1d38)

### Possible workarounds or alternatives

Current issues :
- Painful/errorprone process to create hierarchies involving selecting several instances, right click, chose context menu
- Difficult to see the full hierarchy of a group of object (need to move instances in the scene to check how green arrows are connected)
- Difficult to find and select instances in a scene (ZOrder bar is confusing and not meant for this, difficult to lock/unlock layers, need to move instances that are on top of each other)

### Proposed solution

**Here are the most important features Hierarchy View itself should support :**

- All Instances in the current Layout would be visible in the Hierarchy view so **we can easily drag and drop them** on top of each other t**o create parent/child relationship** (like it works with the new Layer Group feature right now in term of UX)
- **All Instances in the Hierarchy view can be reordered** as the C3 user wants (the user needs to let them in the same "Level" to not change previously created Parent/Child relationship of course) so it's not ordered alphabetically but manually. This way most commonly used object could be placed by user on top of Hierarchy to select them easily (no need to lock everylayer on top of it to select)
- So i can change which object appears at the very top of the Hierarchy view for example, by dragging it at the top (same for children of a specific Object)
- **The User can create Folder at any Level of the Hierarchy View** but they don't have any impact on Hierarchy features. For example it's possible to put all "Entities" Object under a the same Folder so it's easier to find/fold/unfold them later without creating unwanted parent/child relationship
- **Template Feature & Hierarchy View** : if an instance use the Template Feature a symbol next to the Object Type name to show if it's replica 🟡 or a template source 🟢, + the name of the Template between parenthesis after the Object Type Name
- **A Search Field**

**Instance Names** 

- Add a common **"Instance name" property that overrides the default ObjectType Name for that instance in the Hierarchy View**.
- Would help a ton to quickly find a specific instance.
- The search bar would allow us to find instances either : 
     - by typing their Instance Name
     - by typing their ObjectType Name 
     - or by typing their Template Name

### Why is this idea important?

Better way to create Hierarchies
Better way to see parent/child relationships
Better way to find & select instances in a Layout
Better way to display Templates Sources and Replicas.
This is how Scene Tree/Hierarchy work in most of the softwares

**Comment by AshleyScirra** [comment]
New UI is painstaking to develop and so something like this would probably be several month's work.

**Comment by OverboyDev** [comment]
The Hierarchy View works very similarly to the existing Project View.
It doesn't reinvent the wheel at all in term of UI

Anyway this was by far the most wished feature of the 2023 platform (the second implementable feature was only half the number of votes of this one), it was one of the most popular of 2022, and this is already by far the most asked feature of 2024, so I think it's fair to say the common opinion is that it's worth it.

**Comment by NickR-Git** [comment]
> The Hierarchy View works very similarly to the existing Project View. It doesn't reinvent the wheel at all in term of UI elements included in the C3 engine. I deliberately suggestes an implementation working as close as possible to existing feature so you can reuse some stuff.
> 
> (If making a UI very similar to an existing one is so painstaking to develop and would take several months of work for a veteran webdev/engine dev then maybe requiring any C3 user to create their whole UI for their game via HTML/CSS isn't the best idea ? But this is a different topic)
> 
> Anyway this suggestion :
> 
> * is already by far the most asked feature of 2024
> * was by far the most voted feature of the 2023 platform (the second implementable feature was only half the number of votes of this one)
> * was one of the most popular of 2022
> * so I think it's fair to say the common opinion is that it's worth it and very urgent to have.
> 
> We've all been waiting for YEARS already. Construct is the only software I know of (from any category, not only gamedev-related) that has SceneTree/Hierarchy but not a Hierarchy View, this is how any software work, users are used to it, expecting this and this is the most obvious and pleasant workflow.
> 
> Also it kills many birds with 1 stone as it also solve the instance search/select issue in addition to the Hierarchy workflow and visualisation improvements.

Something to consider may be dropping the folders to simplify - this is less common in scene hierarchy views in other engines and more common in a full project view (like you mentioned).

Take a look at how Unity handles it, with the root object of a Prefab being how to organize other objects:
https://docs.unity3d.com/Manual/Hierarchy.html

The one obvious difference here is that Unity allows empty/null objects to be used as a root object to manage multiple other objects (single or made of prefabs), and there isn't currently an equivalent in C3.

Something else to consider is the functionality behind the UI - being and to drag/drop objects to define hierarchies as you go, including objects that could potentially be set up with other parent/child relationships - is very different than displaying layers/sublayers or project files in folders, even if it looks the same on the surface.

**Comment by OverboyDev** [comment]
> Something to consider may be dropping the folders to simplify - this is less common in scene hierarchy views in other engines and more common in a full project view (like you mentioned).

I agree Folder isn't common to all Hierarchy Views, but that implementation is tailored to Construct 3 and essential in my opinion :
- First, it's already the workflow we're using in Project View, the same way to display stuff.
- No need to create a new dumb Sprite that won't be used in gameplay, add a folder logo image to it, put it on the layout just so it appears in the Hierarchy View to create a category (just create an actual Folder in hierarchy View instead)
- If we needed to put actual dumb/empty Objects to organize things, then we wouldn't be able to use Pick Own Children/Pick Own Parent conditions in our code, it would unnecesseraly complexify any system using EventSheet while hierarchy-based systems already allow to workaround many limitations of the engine by allowing to create Composite Pattern or Complex Data Containers. I'm using Hierarchy in all my systems, and if would totally drop the organisation if it required to do more complex picking each time i need to access a parent or a child. ("Pick All Children" can pick wrong instances while i just want direct children)
- Allowing for the Hierarchy View to create folders that don't create parent/child relationship isn't complex to implement. The engine just need to consider the actual parent of the object is the parent object of its parent folder.
 

> Something else to consider is the functionality behind the UI - being and to drag/drop objects to define hierarchies as you go, unique to a scene or even a single instance, including objects that could potentially be set up with other parent/child relationships - is very different than displaying layers/sublayers or project files in folders, even if it looks the same on the surface.

Of course the functionnalities between a Project View and a Hierarchy View are different.
But the "painstaking" part seems to be the UI part according to Scirra.

My point is that the UI part of Project View is already fully implemented, polished and bug-free (it's already a hierarchical way to display elements, you can drag and drop them, create folder etc...) and the proposed  implementation of the Hierarchy View works very similarly.
(Layers View which now supports Sublayers is a second place working similarly to the Project View in term of UI features)

The functionnalities already exist too : We can already create and remove parent/child relationship via Right-click context menu on the Layout.

So most of the UI already exist or at least the whole R&D/Polish/Bugfix is done + the functionnalities already exists.

I'm not saying it's easy or would take only a day to do but i doubt it would take several full-time month of work. 
Which is the only thing Scirra ever said about what has been the most asked feature for 2/3 years, while it solve many issues of the engine in 1 shot.

**Comment by NickR-Git** [comment]
> I agree Folder isn't common to all Hierarchy Views, but that implementation is tailored to Construct 3 and essential in my opinion :
> 
> * First, it's already the workflow we're using in Project View, the same way to display and organize stuff. (=> intuitive)
> * No need to create a new dumb Sprite that won't be used in gameplay, add a folder logo image to it, put it on the layout, set it to invisible, just so it appears in the Hierarchy View every single time we need to create a Fake Folder (Just create an actual Folder in hierarchy View instead)
> * As opposed to Unity, moving/turning a Hierarchy parent doesn't move/rescale its children by default. There is no point to have empty/dumb parent objects most of the time
> * "Object-based Fake Folders" would also pollute the Layout View with green arrows crossing the whole screen, like what if you have a "Environment" fake folders linked to every Rock/Tree/Grass ?
> * The Folder would change its icon when expanded/collapsed as in Project View (impossible for dumb Sprites)
> * The Folder could have a different right click context menu with different options than actual GameObjects
> * If we needed to put actual dumb/empty Objects to organize things, then we wouldn't be able to use Pick Own Children/Pick Own Parent conditions in our code, it would unnecesseraly complexify any system using Hierarchy while hierarchy-based systems already allow to workaround many limitations of the engine by allowing to create Composite Pattern or Complex Data Containers (useful in a engine without proper Inheritance/Nested Family support and with only number/string/bool variables among many other limitations).
> * I'm using Hierarchy in all my systems, and I would totally drop the organisation aspect if it required to do more complex picking each time i need to access a parent or a child, as what should be just direct parent could become great great grandparent because of "Fake Folders". ("Pick All Children" can pick wrong instances while i just want direct children, so i would need to create extra variables, manual ID, extra conditions in all my eventblocks)
> * Allowing for the Hierarchy View to create folders that don't create parent/child relationship isn't complex to implement. The engine just need to consider the actual parent of the object is the parent object of its parent folder + the Folder feature is already implemented similarly in Project View
> 

You're understating the complexity of a lot of functionality here. Let's start at the top:

- Workflows aren't the same as the functionality behind them. While visually reorganizing objects in a scene may be similar in functionality _to the end user_, regardless of the engine being used, what the UI is doing behind the scenes to make/create object linkages in a hierarchy is just wildly different.

- This is new functionality that doesn't exist, and using folders for multiple purposes creates confusion for the end user. You're calling the solution used elsewhere in all major game engines "dumb," while describing an interface that does exactly the same thing, but uses folders as null objects - which is not what folders are for in any computer system ever developed.

-  This would be useful functionality, which is why it's in every other engine with a hierarchy view.

- You should probably stop saying it's the same functionality as the existing Project View, then go on to describe the new functionality that would be needed to do what you're suggesting. And nobody said green arrows needed to be shooting everywhere. You're confusing things and likely yourself by making assumptions.

- If you mix folders functionality with new functionality not normally connected to folder structures, sure, you could potentially be creating picking problems - if once again you ignore this is a solved issue in other engines which use a "standard" hierarchy view as appears in not only other game engines, but _every other piece of software with a hierarchy view_.


> Of course the functionnalities between a Project View and a Hierarchy View are different.
> But the "painstaking" part seems to be the UI part according to Scirra.

- I don't get the impression from Ashely's response that this was the sole concern in implementing the proposed functionality.

> My point is that the UI part of Project View is already fully implemented, polished and bug-free (it's already a hierarchical way to display elements, you can drag and drop them, create folder etc...) and the proposed implementation of the Hierarchy View works very similarly.

Your point is understood but misinformed. There's a lot of complexity buried in your request. I am 100% in agreement that C3 needs a hierarchy view but there's no need to reinvent the wheel in the most overly convoluted way to do so, some of which is being done in the original post and your response to my comments.

> (Layers View which now supports Sublayers is a second place working similarly to the Project View in term of UI features)

Not really. Again, what the end user sees is not the same as what's going on under the hood.

> The functionnalities already exist too : We can already create and remove parent/child relationship via Right-click context menu on the Layout.

Drag & drop functionality to build object hierarchies does not currently exist and it's not as simple as calling the same function called on right-click to make it happen.

> 
> So most of the UI already exist or at least the whole Implementation/R&D/Polish/Bugfix is done + the functionnalities already exists.
 
Again, nope. I'm not the developer and even I know this isn't how things work, in C3 or elsewhere.

> I'm not saying it's easy or would take only a day to do, but i doubt it would take several full-time month of work.
> Which is the only thing Scirra ever said about what has been the most asked feature for 2/3 years, while it solve many issues of the engine in 1 shot and was designed to be as close as possible to existing C3 UI, workflow, philosophy and features

It's easily months of work for a single developer. And from what I can tell from previous rounds, it is not and has never been the most asked for feature - and again, I agree it would be invaluable and save a lot of time - but resorting to hyperbole isn't going to get anything done.

**Comment by DiegoScirra** [comment]
This feature is now in development.

Out of everything mentioned the only thing that will be skipped for an initial release is the **instance name**. This is because even though just adding the field is relatively easy, I can foresee a lot of related work just because it would be the expected.

A few cases I can think of are:

1. Using this new field in the Z Order Bar and Timeline Bar to refer to specific instances, both because it would look good and because it would be strange that is not used in similar places.
2. Adding the expected actions conditions and expressions that should work with that value. It would effectively work as an easier to use UID.
3. Supporting the corresponding scripting interfaces.

There might be more things that would just feel "natural" if that property is added.

So the initial release will just refer to each instance by the object type name followed by the UID (how the Z Order Bar and Timeline Bar already do it). From working on it, it seems that being able to use sub folders and getting the feedback of clicking on the bar and having the corresponding instances selected on the layout view already make it pretty convenient to identify individual instances.

**Comment by OverboyDev** [comment]
Amazing thank you @DiegoScirra, can't wait to try the Hierarchy View feature 🙏

Very cool also to know you plan to implement instance names at some point, indeed it would be awesome if it also worked for Z Order Bar, Timeline Bar and if it comes with user-friendly ACE !

**Comment by DiegoScirra** [comment]
@CrackHub 

This is a different feature that has nothing to do with z ordering. File a new suggestion for that.

Try to explain as best as you can **EXACTLY** what is it that you want. Vague suggestions often don't gather too much attention or worse, might end up being implemented differently to what you were expecting.

**Comment by DiegoScirra** [comment]
This feature will go out in the next beta cycle.

The new bar ended up being a little bit different to the feature request, I decided to call it **Instance Bar**, because it's a general purpose control rather than something specifically used for hierarchies and templates.

Hierarchies are shown in a natural way in the shape of a tree, template information on the other hand ends up being tacked on, makes you think that anything else could be shown instead. Because of that, there will be options to choose what additional information you want to tack on and templates are just one of those options.

The next beta will also add a new **"Tags"** property to all instances, this will work as the **Instance Name** that was described in the request, with the addition that instances will be able to have many tags.

As expected tags end up working in a similar way to UIDs, but since they are string names you can control and can be duplicated, they end up being much more useful. This comes with the expected ACEs and scripting API support to work with tags.

Someone might expect that since tags are similar to UIDs that there will be similar ACEs and scripting interfaces added in all the places where UIDs are somehow supported... the truth is that doing that would take a long time and honestly I don't think it would be that useful, so we decided to ignore that part for now in order to get something out that I think a lot of people will find rather useful in it's current state.

**Comment by AshleyScirra** [comment]
The first release of this feature is now available in [r398](https://www.construct.net/en/make-games/releases/beta/r398). Work will doubtless continue for the next release cycle or two as further improvements are made in response to feedback, but as the feature has now shipped, updating this feature request as such.

**Comment by XHXIAIEIN** [comment]
Thank you so much for your work!  
I've found that currently can only lock/visible the layer, but cannot make changes to the instance objects, I think supporting this will help better use it: 
https://github.com/Scirra/Construct-feature-requests/issues/226
