### ISSUE TITLE
Auto-suggestion for tags

### ISSUE THREAD

**Issue by KhaledFelfal** [Scirra/Construct-feature-requests#96]
### Reviewed guidelines

- [X] I have read and understand the suggestion guidelines

### Checked for duplicate suggestions

- [X] I checked for existing similar suggestions

### Summary

This feature would be useful in situations where you have to type tags (For anything that has 'Tag' field). It’s easy to make a typo or misspell a tag, which can cause issues with code execution. With this feature, the system would automatically suggest the correct tag based on what you’ve typed so far. This would work in a similar way to how the system suggests object names when you start typing them. The auto-suggestion feature would help you save time and avoid errors caused by typos or incorrect capitalization. 
![image](https://github.com/Scirra/Construct-feature-requests/assets/62517244/6fa53399-02c1-4c3e-84df-86bf83259c06)

### Possible workarounds or alternatives

There's no way to achieve this currently.

### Proposed solution

The auto-suggestion feature would be implemented as follows:
When the user starts typing a tag, the system would automatically suggest a list of tags that match the letters typed so far. Based on previously used tags.

### Why is this idea important?

It's more of ecosystem feature so that this field can work as other fields with auto-suggestion.

**Comment by NukeThemAllGame** [comment]
I also want this! Would be very helpful. How many times my code broke because i misspelled the timer name by wrong letter or Captitalization

**Comment by fodi** [comment]
I have a workaround I've been using for this sort of thing: instead of using string literals in tags (animation names, layer names, et cetera), I create global constants that act as "macros" (eg. one named TIMER_PrologueText which has the value "PrologueText"). That way you not only get the autocompletion, but you can always rename it just by editing the constant (no need to run a search and replace) and you can also use "find all references" on it to quickly list all actions/conditions where you used that timer tag.

**Comment by CrackHub** [comment]
Also I want see this in tweens.

**Comment by AshleyScirra** [comment]
Autocomplete for tags is now supported in [r394](https://www.construct.net/en/make-games/releases/beta/r394), covering timers, tweens, signals, and lots more.

**Comment by XHXIAIEIN** [comment]
@AshleyScirra Autocompletion for project files is not currently covered. https://github.com/Scirra/Construct-feature-requests/issues/162
